#This abstracts the generated source files in the design. DO NOT EDIT. This document is generated by PSoC Creator design builds.

GEN_SOURCE_DIR= Generated_Source/PSoC5

GEN_C_SOURCE_CortexM3=\
	$(GEN_SOURCE_DIR)/USBUART.c\
	$(GEN_SOURCE_DIR)/USBUART_audio.c\
	$(GEN_SOURCE_DIR)/USBUART_boot.c\
	$(GEN_SOURCE_DIR)/USBUART_cdc.c\
	$(GEN_SOURCE_DIR)/USBUART_cls.c\
	$(GEN_SOURCE_DIR)/USBUART_descr.c\
	$(GEN_SOURCE_DIR)/USBUART_drv.c\
	$(GEN_SOURCE_DIR)/USBUART_episr.c\
	$(GEN_SOURCE_DIR)/USBUART_hid.c\
	$(GEN_SOURCE_DIR)/USBUART_pm.c\
	$(GEN_SOURCE_DIR)/USBUART_std.c\
	$(GEN_SOURCE_DIR)/USBUART_vnd.c\
	$(GEN_SOURCE_DIR)/USBUART_midi.c\
	$(GEN_SOURCE_DIR)/USBUART_msc.c\
	$(GEN_SOURCE_DIR)/USBUART_Dm.c\
	$(GEN_SOURCE_DIR)/USBUART_Dp.c\
	$(GEN_SOURCE_DIR)/CyDmac.c\
	$(GEN_SOURCE_DIR)/CyFlash.c\
	$(GEN_SOURCE_DIR)/CyLib.c\
	$(GEN_SOURCE_DIR)/cyPm.c\
	$(GEN_SOURCE_DIR)/CySpc.c\
	$(GEN_SOURCE_DIR)/cyutils.c\
	$(GEN_SOURCE_DIR)/cy_em_eeprom.c\
	$(GEN_SOURCE_DIR)/UART.c\
	$(GEN_SOURCE_DIR)/UART_PM.c\
	$(GEN_SOURCE_DIR)/UART_INT.c\
	$(GEN_SOURCE_DIR)/UART_BOOT.c\
	$(GEN_SOURCE_DIR)/UART_IntClock.c\
	$(GEN_SOURCE_DIR)/MotorEncoderA.c\
	$(GEN_SOURCE_DIR)/MotorEncoderA_PM.c\
	$(GEN_SOURCE_DIR)/MotorEncoderA_INT.c\
	$(GEN_SOURCE_DIR)/M1Y.c\
	$(GEN_SOURCE_DIR)/M1X.c\
	$(GEN_SOURCE_DIR)/MotorEncoderB.c\
	$(GEN_SOURCE_DIR)/MotorEncoderB_PM.c\
	$(GEN_SOURCE_DIR)/MotorEncoderB_INT.c\
	$(GEN_SOURCE_DIR)/M2X.c\
	$(GEN_SOURCE_DIR)/M2Y.c\
	$(GEN_SOURCE_DIR)/MotorEncoderC.c\
	$(GEN_SOURCE_DIR)/MotorEncoderC_PM.c\
	$(GEN_SOURCE_DIR)/MotorEncoderC_INT.c\
	$(GEN_SOURCE_DIR)/M3X.c\
	$(GEN_SOURCE_DIR)/M3Y.c\
	$(GEN_SOURCE_DIR)/MotorEncoderA_Cnt16.c\
	$(GEN_SOURCE_DIR)/MotorEncoderA_Cnt16_PM.c\
	$(GEN_SOURCE_DIR)/MotorEncoderB_Cnt16.c\
	$(GEN_SOURCE_DIR)/MotorEncoderB_Cnt16_PM.c\
	$(GEN_SOURCE_DIR)/MotorEncoderC_Cnt16.c\
	$(GEN_SOURCE_DIR)/MotorEncoderC_Cnt16_PM.c\
	$(GEN_SOURCE_DIR)/MotorEncoderA_isr.c\
	$(GEN_SOURCE_DIR)/MotorEncoderB_isr.c\
	$(GEN_SOURCE_DIR)/MotorEncoderC_isr.c\
	$(GEN_SOURCE_DIR)/EncoderClock.c\
	$(GEN_SOURCE_DIR)/EncoderClock_1.c\
	$(GEN_SOURCE_DIR)/BLDCDriver_1_PulseGenerator.c\
	$(GEN_SOURCE_DIR)/BLDCDriver_1_PulseGenerator_PM.c\
	$(GEN_SOURCE_DIR)/EncoderClock_2.c

GEN_ASM_SOURCE_CortexM3=\
	$(GEN_SOURCE_DIR)/CyBootAsmGnu.s

GEN_SEP_C_SOURCE_CortexM3=\
	$(GEN_SOURCE_DIR)/cyfitter_cfg.c\
	$(GEN_SOURCE_DIR)/cymetadata.c\
	$(GEN_SOURCE_DIR)/Cm3Start.c

GEN_LIBS_CortexM3=\
	Export/ARM_GCC_Generic/CyComponentLibrary.a

