/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "UART.h"
#include "M1X_aliases.h"
#include "M1X.h"
#include "M1nReset_aliases.h"
#include "M1nReset.h"
#include "M1PWMs_aliases.h"
#include "M1PWMs.h"
#include "BLDCClock.h"
#include "M1Y_aliases.h"
#include "M1Y.h"
#include "M1H_aliases.h"
#include "M1H.h"
#include "Control.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "UART_IntClock.h"
#include "BLDCMotor_1_HallEncoder.h"
#include "BLDCMotor_1_PWM.h"
#include "BLDCMotor_1_ControlInterrupt.h"
#include "BLDCMotor_1_QEIEncoder.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

